[build]
  # Serve files from repo root (static index.html)
  publish = "."
  # No build command needed
  command = ""

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
